---

- name: OTP | check if install exists
  stat:
    path: "{{ otp_install_dir }}/bin/erl"
  register: otp_exists

- name: OTP | get from git repository
  git: repo="{{ otp_repo_url }}"
       dest="{{ otp_tmp }}"
       version="{{ version }}"
  when: not otp_exists.stat.exists
  register: otp_downloaded

- name: OTP | Configure
  become: true
  shell: chdir={{otp_tmp}} ./configure --prefix={{otp_install_dir}}
  when: otp_extract.changed
  register: otp_configure

- name: OTP | Make
  become: true
  shell: chdir={{otp_tmp}} make
  when: otp_configure.changed
  register: otp_make

- name: OTP | Install
  become: true
  shell: chdir={{otp_tmp}} make install
  when: otp_make.changed
  register: otp_install

- name: OTP | add path to /etc/profile.d/otp_path.sh
  become: true
  action: template src=otp_path.sh.j2
          dest="/etc/profile.d/otp_path.sh"
          mode=0644
  when: otp_install.changed

- name: OTP | cleanup tmp
  become: true
  file:
    path: "{{ otp_tmp }}"
    state: absent
  when: otp_install.changed

...
