---

- name: OTP | check if install exists
  stat:
    path: "{{ otp_install_dir }}"
  register: otp_exists

- name: OTP | get from git repository
  git: repo="{{ otp_repo_url }}"
       dest="{{ otp_tmp }}"
       version="{{ otp_version }}"
  when: not otp_exists.stat.exists
  register: otp_downloaded

- name: OTP | Configure
  become: true
  shell: chdir={{otp_tmp}} ./configure --prefix={{otp_install_dir}}
  when: otp_downloaded.changed
  register: otp_configure

- name: OTP | Make
  become: true
  shell: chdir={{otp_tmp}} make
  when: otp_configure.changed
  register: otp_make

- name: OTP | Install
  become: true
  shell: chdir={{otp_tmp}} make install
  when: otp_make.changed
  register: otp_install

- name: OTP | create a symlink
  file:
    src: "{{ otp_install_dir }}/bin/{{ item.path }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    state: link
  with_items:
    - { path: 'erl', dest: 'erl' }
    - { path: 'erlc', dest: 'erlc' }
    - { path: 'ct_run', dest: 'ct_run' }
    - { path: 'dialyzer', dest: 'dialyzer' }
    - { path: 'epmd', dest: 'epmd' }
    - { path: 'escript', dest: 'escript' }
    - { path: 'run_erl', dest: 'run_erl' }
    - { path: 'to_erl', dest: 'to_erl' }
    - { path: 'typer', dest: 'typer' }

- name: OTP | cleanup tmp
  become: true
  file:
    path: "{{ otp_tmp }}"
    state: absent
  when: otp_install.changed

...
