---

- name: Elixir | check current elixir version
  debug:
    msg: "elixir version: {{ ansible_local.otp.elixir_version | default( 0 ) }}"

- name: Elixir | Get Elixir sources
  become: true
  get_url: url="{{ elixir_url }}" dest="{{ elixir_tmp }}" timeout=180 force=no
  when: ( ansible_local.otp.elixir_version | default( 0 ) != elixir_version )
  register: elixir_downloaded

- name: Elixir | Extract Elixir sources
  become: true
  unarchive: src="{{ elixir_tmp }}"
             dest="/tmp"
             creates="{{ elixir_build }}"
             remote_src=yes
  when: elixir_downloaded.changed
  register: elixir_extract

- name: Elixir | Make
  become: true
  shell: chdir="{{elixir_build}}" make
  when: elixir_extract.changed
  register: elixir_make

- name: Elixir | Install
  become: true
  shell: chdir="{{elixir_build}}" make install
  when: elixir_make.changed
  register: elixir_install

- name: Elixir | Create a directory for custom facts /etc/ansible/facts.d
  file:
    path: /etc/ansible/facts.d
    state: directory
    recurse: yes
    mode: '0644'
  when: elixir_install.changed
  become: true

- name: Elixir | add opt version customfact into /etc/ansible/facts.d
  action: template src=otp.fact-template.j2
          dest="/etc/ansible/facts.d/otp.fact"
          mode=0644
  when: elixir_install.changed
  become: true
  
- name: Elixir | cleanup tmp
  become: true
  file:
    path: "{{ elixir_tmp }}"
    state: absent
  when: elixir_install.changed

...
